services:
  # API Gateway Service
  api-gateway:
    build:
      context: ../..
      dockerfile: api_gateway/docker/Dockerfile
    container_name: api_gateway
    ports:
      - "8000:8000"
    env_file:
      - ../.env
    networks:
      - ecommerce-network
    restart: unless-stopped

networks:
  ecommerce-network:
    external: true
