version: "3.8"

# 🏪 E-commerce Microservices - Simplified Observability Stack
# =============================================================
# This simplified version uses more commonly available images

services:
  # ========================================
  # 📊 ELK STACK - LOG AGGREGATION
  # ========================================

  elasticsearch:
    image: elasticsearch:7.17.0
    container_name: ecommerce_elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - observability

  kibana:
    image: kibana:7.17.0
    container_name: ecommerce_kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - observability
    depends_on:
      - elasticsearch

  # ========================================
  # 🔍 DISTRIBUTED TRACING
  # ========================================

  jaeger:
    image: jaegertracing/all-in-one:1.35
    container_name: ecommerce_jaeger
    ports:
      - "16686:16686" # Jaeger UI
      - "14268:14268" # HTTP collector
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - observability

  # ========================================
  # 📈 METRICS AND MONITORING
  # ========================================

  prometheus:
    image: prom/prometheus:v2.35.0
    container_name: ecommerce_prometheus
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.enable-lifecycle"
    networks:
      - observability

  grafana:
    image: grafana/grafana:8.5.0
    container_name: ecommerce_grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_USERS_ALLOW_SIGN_UP=false
    networks:
      - observability

volumes:
  elasticsearch_data:
    driver: local
  prometheus_data:
    driver: local
  grafana_data:
    driver: local

networks:
  observability:
    driver: bridge
    name: ecommerce_observability
