"""
This type stub file was generated by pyright.
"""

from typing import Union
from typing_extensions import Literal

CodecNoneT = Literal[0]
CodecGzipT = Literal[1]
CodecSnappyT = Literal[2]
CodecLz4T = Literal[3]
CodecZstdT = Literal[4]
CodecMaskT = Literal[7]
DefaultCompressionTypeT = Union[CodecGzipT, CodecLz4T, CodecNoneT, CodecSnappyT, CodecZstdT]
LegacyCompressionTypeT = Union[CodecGzipT, CodecLz4T, CodecSnappyT, CodecNoneT]
