
apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090
    isDefault: true
    
  - name: Jaeger
    type: jaeger
    url: http://jaeger-all-in-one:16686
    
  - name: Tempo
    type: tempo
    url: http://jaeger-all-in-one:3200
