"""
This type stub file was generated by pyright.
"""

from .content import Content

class AmpHtmlContent(Content):
    """AMP HTML content to be included in your email."""
    def __init__(self, content) -> None:
        """Create an AMP HTML Content with the specified MIME type and content.

        :param content: The AMP HTML content.
        :type content: string
        """
        ...
    
    @property
    def mime_type(self): # -> Literal['text/x-amp-html']:
        """The MIME type for AMP HTML content.

        :rtype: string
        """
        ...
    
    @property
    def content(self): # -> None:
        """The actual AMP HTML content.

        :rtype: string
        """
        ...
    
    @content.setter
    def content(self, value): # -> None:
        """The actual AMP HTML content.

        :param value: The actual AMP HTML content.
        :type value: string
        """
        ...
    
    def get(self): # -> dict[Any, Any]:
        """
        Get a JSON-ready representation of this AmpContent.

        :returns: This AmpContent, ready for use in a request body.
        :rtype: dict
        """
        ...
    


