"""
This type stub file was generated by pyright.
"""

class Asm:
    """An object specifying unsubscribe behavior."""
    def __init__(self, group_id, groups_to_display=...) -> None:
        """Create an ASM with the given group_id and groups_to_display.

        :param group_id: ID of an unsubscribe group
        :type group_id: GroupId, int, required
        :param groups_to_display: Unsubscribe groups to display
        :type groups_to_display: GroupsToDisplay, list(int), optional
        """
        ...
    
    @property
    def group_id(self): # -> GroupId | None:
        """The unsubscribe group to associate with this email.

        :rtype: GroupId
        """
        ...
    
    @group_id.setter
    def group_id(self, value): # -> None:
        """The unsubscribe group to associate with this email.

        :param value: ID of an unsubscribe group
        :type value: GroupId, int, required
        """
        ...
    
    @property
    def groups_to_display(self): # -> GroupsToDisplay | None:
        """The unsubscribe groups that you would like to be displayed on the
        unsubscribe preferences page. Max of 25 groups.

        :rtype: GroupsToDisplay
        """
        ...
    
    @groups_to_display.setter
    def groups_to_display(self, value): # -> None:
        """An array containing the unsubscribe groups that you would like to
        be displayed on the unsubscribe preferences page. Max of 25 groups.

        :param groups_to_display: Unsubscribe groups to display
        :type groups_to_display: GroupsToDisplay, list(int), optional
        """
        ...
    
    def get(self): # -> dict[Any, Any]:
        """
        Get a JSON-ready representation of this ASM object.

        :returns: This ASM object, ready for use in a request body.
        :rtype: dict
        """
        ...
    


