"""
This type stub file was generated by pyright.
"""

class BatchId:
    """This ID represents a batch of emails to be sent at the same time.
       Including a batch_id in your request allows you include this email
       in that batch, and also enables you to cancel or pause the delivery
       of that batch. For more information, see
       https://sendgrid.com/docs/API_Reference/Web_API_v3/cancel_schedule_send.
    """
    def __init__(self, batch_id=...) -> None:
        """Create a batch ID.

        :param batch_id: Batch Id
        :type batch_id: string
        """
        ...
    
    @property
    def batch_id(self): # -> None:
        """The batch ID.

        :rtype: string
        """
        ...
    
    @batch_id.setter
    def batch_id(self, value): # -> None:
        """The batch ID.

        :param value: Batch Id
        :type value: string
        """
        ...
    
    def __str__(self) -> str:
        """Get a JSON representation of this object.

        :rtype: string
        """
        ...
    
    def get(self): # -> None:
        """
        Get a JSON-ready representation of this BatchId object.

        :returns: The BatchId, ready for use in a request body.
        :rtype: string
        """
        ...
    


