"""
This type stub file was generated by pyright.
"""

class BccSettingsEmail:
    """The BccSettingsEmail of an Attachment."""
    def __init__(self, bcc_settings_email=...) -> None:
        """Create a BccSettingsEmail object

        :param bcc_settings_email: The email address that you would like to
                                   receive the BCC
        :type bcc_settings_email: string, optional
        """
        ...
    
    @property
    def bcc_settings_email(self): # -> None:
        """The email address that you would like to receive the BCC

        :rtype: string
        """
        ...
    
    @bcc_settings_email.setter
    def bcc_settings_email(self, value): # -> None:
        """The email address that you would like to receive the BCC

        :param value: The email address that you would like to receive the BCC
        :type value: string
        """
        ...
    
    def get(self): # -> None:
        """
        Get a JSON-ready representation of this BccSettingsEmail.

        :returns: This BccSettingsEmail, ready for use in a request body.
        :rtype: string
        """
        ...
    


