"""
This type stub file was generated by pyright.
"""

class BccSettings:
    """Settings object for automatic BCC.

    This allows you to have a blind carbon copy automatically sent to the
    specified email address for every email that is sent.
    """
    def __init__(self, enable=..., email=...) -> None:
        """Create a BCCSettings.

        :param enable: Whether this BCCSettings is applied to sent emails.
        :type enable: boolean, optional
        :param email: Who should be BCCed.
        :type email: BccSettingEmail, optional
        """
        ...
    
    @property
    def enable(self): # -> None:
        """Indicates if this setting is enabled.

        :rtype: boolean
        """
        ...
    
    @enable.setter
    def enable(self, value): # -> None:
        """Indicates if this setting is enabled.

        :type param: Indicates if this setting is enabled.
        :type value: boolean
        """
        ...
    
    @property
    def email(self): # -> None:
        """The email address that you would like to receive the BCC.

        :rtype: string
        """
        ...
    
    @email.setter
    def email(self, value): # -> None:
        """The email address that you would like to receive the BCC.

        :param value: The email address that you would like to receive the BCC.
        :type value: string
        """
        ...
    
    def get(self): # -> dict[Any, Any]:
        """
        Get a JSON-ready representation of this BCCSettings.

        :returns: This BCCSettings, ready for use in a request body.
        :rtype: dict
        """
        ...
    


