"""
This type stub file was generated by pyright.
"""

class BypassUnsubscribeManagement:
    """Setting for Bypass Unsubscribe Management


    Allows you to bypass the global unsubscribe list to ensure that the email is delivered to recipients.
    Bounce and spam report lists will still be checked; addresses on these other lists will not receive
    the message. This filter applies only to global unsubscribes and will not bypass group unsubscribes.
    This filter cannot be combined with the bypass_list_management filter.
    """
    def __init__(self, enable=...) -> None:
        """Create a BypassUnsubscribeManagement.

        :param enable: Whether emails should bypass unsubscribe management.
        :type enable: boolean, optional
        """
        ...
    
    @property
    def enable(self): # -> None:
        """Indicates if this setting is enabled.

        :rtype: boolean
        """
        ...
    
    @enable.setter
    def enable(self, value): # -> None:
        """Indicates if this setting is enabled.

        :param value: Indicates if this setting is enabled.
        :type value: boolean
        """
        ...
    
    def get(self): # -> dict[Any, Any]:
        """
        Get a JSON-ready representation of this BypassUnsubscribeManagement.

        :returns: This BypassUnsubscribeManagement, ready for use in a request body.
        :rtype: dict
        """
        ...
    


