"""
This type stub file was generated by pyright.
"""

class BypassListManagement:
    """Setting for Bypass List Management

    Allows you to bypass all unsubscribe groups and suppressions to ensure that
    the email is delivered to every single recipient. This should only be used
    in emergencies when it is absolutely necessary that every recipient
    receives your email.
    """
    def __init__(self, enable=...) -> None:
        """Create a BypassListManagement.

        :param enable: Whether emails should bypass list management.
        :type enable: boolean, optional
        """
        ...
    
    @property
    def enable(self): # -> None:
        """Indicates if this setting is enabled.

        :rtype: boolean
        """
        ...
    
    @enable.setter
    def enable(self, value): # -> None:
        """Indicates if this setting is enabled.

        :param value: Indicates if this setting is enabled.
        :type value: boolean
        """
        ...
    
    def get(self): # -> dict[Any, Any]:
        """
        Get a JSON-ready representation of this BypassListManagement.

        :returns: This BypassListManagement, ready for use in a request body.
        :rtype: dict
        """
        ...
    


