"""
This type stub file was generated by pyright.
"""

class BypassBounceManagement:
    """Setting for Bypass Bounce Management


    Allows you to bypass the bounce list to ensure that the email is delivered to recipients.
    Spam report and unsubscribe lists will still be checked; addresses on these other lists
    will not receive the message. This filter cannot be combined with the bypass_list_management filter.
    """
    def __init__(self, enable=...) -> None:
        """Create a BypassBounceManagement.

        :param enable: Whether emails should bypass bounce management.
        :type enable: boolean, optional
        """
        ...
    
    @property
    def enable(self): # -> None:
        """Indicates if this setting is enabled.

        :rtype: boolean
        """
        ...
    
    @enable.setter
    def enable(self, value): # -> None:
        """Indicates if this setting is enabled.

        :param value: Indicates if this setting is enabled.
        :type value: boolean
        """
        ...
    
    def get(self): # -> dict[Any, Any]:
        """
        Get a JSON-ready representation of this BypassBounceManagement.

        :returns: This BypassBounceManagement, ready for use in a request body.
        :rtype: dict
        """
        ...
    


