"""
This type stub file was generated by pyright.
"""

class Category:
    """A category name for this message."""
    def __init__(self, name=...) -> None:
        """Create a Category.

        :param name: The name of this category
        :type name: string, optional
        """
        ...
    
    @property
    def name(self): # -> None:
        """The name of this Category. Must be less than 255 characters.

        :rtype: string
        """
        ...
    
    @name.setter
    def name(self, value): # -> None:
        """The name of this Category. Must be less than 255 characters.

        :param value: The name of this Category. Must be less than 255
                      characters.
        :type value: string
        """
        ...
    
    def get(self): # -> None:
        """
        Get a JSON-ready representation of this Category.

        :returns: This Category, ready for use in a request body.
        :rtype: string
        """
        ...
    


