"""
This type stub file was generated by pyright.
"""

class ClickTracking:
    """Allows you to track whether a recipient clicked a link in your email."""
    def __init__(self, enable=..., enable_text=...) -> None:
        """Create a ClickTracking to track clicked links in your email.

        :param enable: Whether click tracking is enabled
        :type enable: boolean, optional
        :param enable_text: If click tracking is on in your email's text/plain.
        :type enable_text: boolean, optional
        """
        ...
    
    @property
    def enable(self): # -> None:
        """Indicates if this setting is enabled.

        :rtype: boolean
        """
        ...
    
    @enable.setter
    def enable(self, value): # -> None:
        """Indicates if this setting is enabled.

        :param value: Indicates if this setting is enabled.
        :type value: boolean
        """
        ...
    
    @property
    def enable_text(self): # -> None:
        """Indicates if this setting should be included in the text/plain
        portion of your email.

        :rtype: boolean
        """
        ...
    
    @enable_text.setter
    def enable_text(self, value): # -> None:
        """Indicates if this setting should be included in the text/plain
        portion of your email.

        :param value: Indicates if this setting should be included in the
        text/plain portion of your email.
        :type value: boolean
        """
        ...
    
    def get(self): # -> dict[Any, Any]:
        """
        Get a JSON-ready representation of this ClickTracking.

        :returns: This ClickTracking, ready for use in a request body.
        :rtype: dict
        """
        ...
    


