"""
This type stub file was generated by pyright.
"""

class ContentId:
    """The ContentId of an Attachment."""
    def __init__(self, content_id=...) -> None:
        """Create a ContentId object

        :param content_id: The content id for the attachment.
                           This is used when the Disposition is set to "inline"
                           and the attachment is an image, allowing the file to
                           be displayed within the email body.
        :type content_id: string, optional
        """
        ...
    
    @property
    def content_id(self): # -> None:
        """The content id for the attachment.
           This is used when the Disposition is set to "inline" and the
           attachment is an image, allowing the file to be displayed within
           the email body.

        :rtype: string
        """
        ...
    
    @content_id.setter
    def content_id(self, value): # -> None:
        """The content id for the attachment.
           This is used when the Disposition is set to "inline" and the
           attachment is an image, allowing the file to be displayed within
           the email body.

        :param value: The content id for the attachment.
        This is used when the Disposition is set to "inline" and the attachment
        is an image, allowing the file to be displayed within the email body.
        :type value: string
        """
        ...
    
    def get(self): # -> None:
        """
        Get a JSON-ready representation of this ContentId.

        :returns: This ContentId, ready for use in a request body.
        :rtype: string
        """
        ...
    


