"""
This type stub file was generated by pyright.
"""

class Content:
    """Content to be included in your email.

    You must specify at least one mime type in the Contents of your email.
    """
    def __init__(self, mime_type, content) -> None:
        """Create a Content with the specified MIME type and content.

        :param mime_type: MIME type of this Content (e.g. "text/plain").
        :type mime_type: string
        :param content: The actual content.
        :type content: string
        """
        ...
    
    @property
    def mime_type(self): # -> None:
        """The MIME type of the content you are including in your email.
        For example, "text/plain" or "text/html" or "text/x-amp-html".

        :rtype: string
        """
        ...
    
    @mime_type.setter
    def mime_type(self, value): # -> None:
        """The MIME type of the content you are including in your email.
        For example, "text/plain" or "text/html" or "text/x-amp-html".

        :param value: The MIME type of the content you are including in your
                      email.
        For example, "text/plain" or "text/html" or "text/x-amp-html".
        :type value: string
        """
        ...
    
    @property
    def content(self): # -> None:
        """The actual content (of the specified mime type).

        :rtype: string
        """
        ...
    
    @content.setter
    def content(self, value): # -> None:
        """The actual content (of the specified mime type).

        :param value: The actual content (of the specified mime type).
        :type value: string
        """
        ...
    
    def get(self): # -> dict[Any, Any]:
        """
        Get a JSON-ready representation of this Content.

        :returns: This Content, ready for use in a request body.
        :rtype: dict
        """
        ...
    


