"""
This type stub file was generated by pyright.
"""

class CustomArg:
    """Values that will be carried along with the email and its activity data.

    Substitutions will not be made on custom arguments, so any string entered
    into this parameter will be assumed to be the custom argument that you
    would like to be used. Top-level CustomArgs may be overridden by ones in a
    Personalization. May not exceed 10,000 bytes.
    """
    def __init__(self, key=..., value=..., p=...) -> None:
        """Create a CustomArg with the given key and value.

            :param key: Key for this CustomArg
            :type key: string, optional
            :param value: Value of this CustomArg
            :type value: string, optional
            :param p: p is the Personalization object or Personalization
                      object index
            :type p: Personalization, integer, optional
        """
        ...
    
    @property
    def key(self): # -> None:
        """Key for this CustomArg.

        :rtype: string
        """
        ...
    
    @key.setter
    def key(self, value): # -> None:
        """Key for this CustomArg.

        :param value: Key for this CustomArg.
        :type value: string
        """
        ...
    
    @property
    def value(self): # -> None:
        """Value of this CustomArg.

        :rtype: string
        """
        ...
    
    @value.setter
    def value(self, value): # -> None:
        """Value of this CustomArg.

        :param value: Value of this CustomArg.
        :type value: string
        """
        ...
    
    @property
    def personalization(self): # -> None:
        """The Personalization object or Personalization object index

        :rtype: Personalization, integer
        """
        ...
    
    @personalization.setter
    def personalization(self, value): # -> None:
        """The Personalization object or Personalization object index

        :param value: The Personalization object or Personalization object
                      index
        :type value: Personalization, integer
        """
        ...
    
    def get(self): # -> dict[Any, Any]:
        """
        Get a JSON-ready representation of this CustomArg.

        :returns: This CustomArg, ready for use in a request body.
        :rtype: dict
        """
        ...
    


