"""
This type stub file was generated by pyright.
"""

class Disposition:
    """The content-disposition of the Attachment specifying how you would like
    the attachment to be displayed."""
    def __init__(self, disposition=...) -> None:
        """Create a Disposition object

        :param disposition: The content-disposition of the attachment,
                            specifying display style.
                            Specifies how you would like the attachment to be
                            displayed.
                            - "inline" results in the attached file being
                              displayed automatically within the message.
                            - "attachment" results in the attached file
                              requiring some action to display (e.g. opening
                              or downloading the file).
                            If unspecified, "attachment" is used. Must be one
                            of the two choices.
        :type disposition: string, optional
        """
        ...
    
    @property
    def disposition(self): # -> None:
        """The content-disposition of the attachment, specifying display style.
           Specifies how you would like the attachment to be displayed.
           - "inline" results in the attached file being displayed
             automatically within the message.
           - "attachment" results in the attached file requiring some action to
             display (e.g. opening or downloading the file).
           If unspecified, "attachment" is used. Must be one of the two
           choices.

        :rtype: string
        """
        ...
    
    @disposition.setter
    def disposition(self, value): # -> None:
        """The content-disposition of the attachment, specifying display style.
           Specifies how you would like the attachment to be displayed.
           - "inline" results in the attached file being displayed
             automatically within the message.
           - "attachment" results in the attached file requiring some action to
             display (e.g. opening or downloading the file).
           If unspecified, "attachment" is used. Must be one of the two
           choices.

        :param value: The content-disposition of the attachment, specifying
                      display style.
           Specifies how you would like the attachment to be displayed.
           - "inline" results in the attached file being displayed
             automatically within the message.
           - "attachment" results in the attached file requiring some action to
             display (e.g. opening or downloading the file).
           If unspecified, "attachment" is used. Must be one of the two
           choices.
        :type value: string
        """
        ...
    
    def get(self): # -> None:
        """
        Get a JSON-ready representation of this Disposition.

        :returns: This Disposition, ready for use in a request body.
        :rtype: string
        """
        ...
    


