"""
This type stub file was generated by pyright.
"""

class DynamicTemplateData:
    """To send a dynamic template, specify the template ID with the
       template_id parameter.
    """
    def __init__(self, dynamic_template_data=..., p=...) -> None:
        """Data for a transactional template.
        Should be JSON-serializable structure.

        :param dynamic_template_data: Data for a transactional template.
        :type dynamic_template_data: A JSON-serializable structure
        :param name: p is the Personalization object or Personalization object
                     index
        :type name:  Personalization, integer, optional
        """
        ...
    
    @property
    def dynamic_template_data(self): # -> None:
        """Data for a transactional template.

        :rtype: A JSON-serializable structure
        """
        ...
    
    @dynamic_template_data.setter
    def dynamic_template_data(self, value): # -> None:
        """Data for a transactional template.

        :param value: Data for a transactional template.
        :type value: A JSON-serializable structure
        """
        ...
    
    @property
    def personalization(self): # -> None:
        """The Personalization object or Personalization object index

        :rtype: Personalization, integer
        """
        ...
    
    @personalization.setter
    def personalization(self, value): # -> None:
        """The Personalization object or Personalization object index

        :param value: The Personalization object or Personalization object
                      index
        :type value: Personalization, integer
        """
        ...
    
    def __str__(self) -> str:
        """Get a JSON representation of this object.

        :rtype: A JSON-serializable structure
        """
        ...
    
    def get(self): # -> None:
        """
        Get a JSON-ready representation of this DynamicTemplateData object.

        :returns: Data for a transactional template.
        :rtype: A JSON-serializable structure.
        """
        ...
    


