"""
This type stub file was generated by pyright.
"""

class SendGridException(Exception):
    """Wrapper/default SendGrid-related exception"""
    ...


class ApiKeyIncludedException(SendGridException):
    """Exception raised for when Twilio SendGrid API Key included in message text"""
    def __init__(self, expression=..., message=...) -> None:
        """Create an exception for when Twilio SendGrid API Key included in message text

            :param expression: Input expression in which the error occurred
            :type expression: string
            :param message: Explanation of the error
            :type message: string
        """
        ...
    
    @property
    def expression(self): # -> None:
        """Input expression in which the error occurred

        :rtype: string
        """
        ...
    
    @expression.setter
    def expression(self, value): # -> None:
        """Input expression in which the error occurred

        :param value: Input expression in which the error occurred
        :type value: string
        """
        ...
    
    @property
    def message(self): # -> None:
        """Explanation of the error

        :rtype: string
        """
        ...
    
    @message.setter
    def message(self, value): # -> None:
        """Explanation of the error

        :param value: Explanation of the error
        :type value: string
        """
        ...
    


