"""
This type stub file was generated by pyright.
"""

class FileType:
    """The MIME type of the content you are attaching to an Attachment."""
    def __init__(self, file_type=...) -> None:
        """Create a FileType object

        :param file_type: The MIME type of the content you are attaching
        :type file_type: string, optional
        """
        ...
    
    @property
    def file_type(self): # -> None:
        """The MIME type of the content you are attaching.

        :rtype: string
        """
        ...
    
    @file_type.setter
    def file_type(self, mime_type): # -> None:
        """The MIME type of the content you are attaching.

        :param mime_type: The MIME type of the content you are attaching.
        :rtype mime_type: string
        """
        ...
    
    def get(self): # -> None:
        """
        Get a JSON-ready representation of this FileType.

        :returns: This FileType, ready for use in a request body.
        :rtype: string
        """
        ...
    


