"""
This type stub file was generated by pyright.
"""

class FileName:
    """The filename of an Attachment."""
    def __init__(self, file_name=...) -> None:
        """Create a FileName object

        :param file_name: The file name of the attachment
        :type file_name: string, optional
        """
        ...
    
    @property
    def file_name(self): # -> None:
        """The file name of the attachment.

        :rtype: string
        """
        ...
    
    @file_name.setter
    def file_name(self, value): # -> None:
        """The file name of the attachment.

        :param value: The file name of the attachment.
        :type value: string
        """
        ...
    
    def get(self): # -> None:
        """
        Get a JSON-ready representation of this FileName.

        :returns: This FileName, ready for use in a request body.
        :rtype: string
        """
        ...
    


