"""
This type stub file was generated by pyright.
"""

class FileContent:
    """The Base64 encoded content of an Attachment."""
    def __init__(self, file_content=...) -> None:
        """Create a FileContent object

        :param file_content: The Base64 encoded content of the attachment
        :type file_content: string, optional
        """
        ...
    
    @property
    def file_content(self): # -> None:
        """The Base64 encoded content of the attachment.

        :rtype: string
        """
        ...
    
    @file_content.setter
    def file_content(self, value): # -> None:
        """The Base64 encoded content of the attachment.

        :param value: The Base64 encoded content of the attachment.
        :type value: string
        """
        ...
    
    def get(self): # -> None:
        """
        Get a JSON-ready representation of this FileContent.

        :returns: This FileContent, ready for use in a request body.
        :rtype: string
        """
        ...
    


