"""
This type stub file was generated by pyright.
"""

class FooterHtml:
    """The HTML in a Footer."""
    def __init__(self, footer_html=...) -> None:
        """Create a FooterHtml object

        :param footer_html: The html content of your footer.
        :type footer_html: string, optional
        """
        ...
    
    @property
    def footer_html(self): # -> None:
        """The html content of your footer.

        :rtype: string
        """
        ...
    
    @footer_html.setter
    def footer_html(self, html): # -> None:
        """The html content of your footer.

        :param html: The html content of your footer.
        :type html: string
        """
        ...
    
    def get(self): # -> None:
        """
        Get a JSON-ready representation of this FooterHtml.

        :returns: This FooterHtml, ready for use in a request body.
        :rtype: string
        """
        ...
    


