"""
This type stub file was generated by pyright.
"""

class FooterSettings:
    """The default footer that you would like included on every email."""
    def __init__(self, enable=..., text=..., html=...) -> None:
        """Create a default footer.

        :param enable: Whether this footer should be applied.
        :type enable: boolean, optional
        :param text: Text content of this footer
        :type text: FooterText, optional
        :param html: HTML content of this footer
        :type html: FooterHtml, optional
        """
        ...
    
    @property
    def enable(self): # -> None:
        """Indicates if this setting is enabled.

        :rtype: boolean
        """
        ...
    
    @enable.setter
    def enable(self, value): # -> None:
        """Indicates if this setting is enabled.

        :param value: Indicates if this setting is enabled.
        :type value: boolean
        """
        ...
    
    @property
    def text(self): # -> None:
        """The plain text content of your footer.

        :rtype: string
        """
        ...
    
    @text.setter
    def text(self, value): # -> None:
        """The plain text content of your footer.

        :param value: The plain text content of your footer.
        :type value: string
        """
        ...
    
    @property
    def html(self): # -> None:
        """The HTML content of your footer.

        :rtype: string
        """
        ...
    
    @html.setter
    def html(self, value): # -> None:
        """The HTML content of your footer.

        :param value: The HTML content of your footer.
        :type value: string
        """
        ...
    
    def get(self): # -> dict[Any, Any]:
        """
        Get a JSON-ready representation of this FooterSettings.

        :returns: This FooterSettings, ready for use in a request body.
        :rtype: dict
        """
        ...
    


