"""
This type stub file was generated by pyright.
"""

class FooterText:
    """The text in an Footer."""
    def __init__(self, footer_text=...) -> None:
        """Create a FooterText object

        :param footer_text: The plain text content of your footer.
        :type footer_text: string, optional
        """
        ...
    
    @property
    def footer_text(self): # -> None:
        """The plain text content of your footer.

        :rtype: string
        """
        ...
    
    @footer_text.setter
    def footer_text(self, value): # -> None:
        """The plain text content of your footer.

        :param value: The plain text content of your footer.
        :type value: string
        """
        ...
    
    def get(self): # -> None:
        """
        Get a JSON-ready representation of this FooterText.

        :returns: This FooterText, ready for use in a request body.
        :rtype: string
        """
        ...
    


