"""
This type stub file was generated by pyright.
"""

class GroupsToDisplay:
    """The unsubscribe groups that you would like to be displayed on the
    unsubscribe preferences page.."""
    def __init__(self, groups_to_display=...) -> None:
        """Create a GroupsToDisplay object

        :param groups_to_display: An array containing the unsubscribe groups
                                  that you would like to be displayed on the
                                  unsubscribe preferences page.
        :type groups_to_display: array of integers, optional
        """
        ...
    
    @property
    def groups_to_display(self): # -> None:
        """An array containing the unsubscribe groups that you would like to be
        displayed on the unsubscribe preferences page.

        :rtype: array(int)
        """
        ...
    
    @groups_to_display.setter
    def groups_to_display(self, value): # -> None:
        """An array containing the unsubscribe groups that you would like to be
        displayed on the unsubscribe preferences page.

        :param value: An array containing the unsubscribe groups that you
                      would like to be displayed on the unsubscribe
                      preferences page.
        :type value: array(int)
        """
        ...
    
    def get(self): # -> None:
        """
        Get a JSON-ready representation of this GroupsToDisplay.

        :returns: This GroupsToDisplay, ready for use in a request body.
        :rtype: array of integers
        """
        ...
    


