"""
This type stub file was generated by pyright.
"""

class GroupId:
    """The unsubscribe group ID to associate with this email."""
    def __init__(self, group_id=...) -> None:
        """Create a GroupId object

        :param group_id: The unsubscribe group to associate with this email.
        :type group_id: integer, optional
        """
        ...
    
    @property
    def group_id(self): # -> None:
        """The unsubscribe group to associate with this email.

        :rtype: integer
        """
        ...
    
    @group_id.setter
    def group_id(self, value): # -> None:
        """The unsubscribe group to associate with this email.

        :param value: The unsubscribe group to associate with this email.
        :type value: integer
        """
        ...
    
    def get(self): # -> None:
        """
        Get a JSON-ready representation of this GroupId.

        :returns: This GroupId, ready for use in a request body.
        :rtype: integer
        """
        ...
    


