"""
This type stub file was generated by pyright.
"""

class Header:
    """A header to specify specific handling instructions for your email.

    If the name or value contain Unicode characters, they must be properly
    encoded. You may not overwrite the following reserved headers:
    x-sg-id, x-sg-eid, received, dkim-signature, Content-Type,
    Content-Transfer-Encoding, To, From, Subject, Reply-To, CC, BCC
    """
    def __init__(self, key=..., value=..., p=...) -> None:
        """Create a Header.

        :param key: The name of the header (e.g. "Date")
        :type key: string, optional
        :param value: The header's value (e.g. "2013-02-27 1:23:45 PM PDT")
        :type value: string, optional
        :param name: p is the Personalization object or Personalization object
                     index
        :type name: Personalization, integer, optional
        """
        ...
    
    @property
    def key(self): # -> None:
        """The name of the header.

        :rtype: string
        """
        ...
    
    @key.setter
    def key(self, value): # -> None:
        """The name of the header.

        :param value: The name of the header.
        :type value: string
        """
        ...
    
    @property
    def value(self): # -> None:
        """The value of the header.

        :rtype: string
        """
        ...
    
    @value.setter
    def value(self, value): # -> None:
        """The value of the header.

        :param value: The value of the header.
        :type value: string
        """
        ...
    
    @property
    def personalization(self): # -> None:
        """The Personalization object or Personalization object index

        :rtype: Personalization, integer
        """
        ...
    
    @personalization.setter
    def personalization(self, value): # -> None:
        """The Personalization object or Personalization object index

        :param value: The Personalization object or Personalization object
                      index
        :type value: Personalization, integer
        """
        ...
    
    def get(self): # -> dict[Any, Any]:
        """
        Get a JSON-ready representation of this Header.

        :returns: This Header, ready for use in a request body.
        :rtype: dict
        """
        ...
    


