"""
This type stub file was generated by pyright.
"""

from .content import Content

class HtmlContent(Content):
    """HTML content to be included in your email."""
    def __init__(self, content) -> None:
        """Create an HtmlContent with the specified MIME type and content.

        :param content: The HTML content.
        :type content: string
        """
        ...
    
    @property
    def mime_type(self): # -> Literal['text/html']:
        """The MIME type for HTML content.

        :rtype: string
        """
        ...
    
    @property
    def content(self): # -> None:
        """The actual HTML content.

        :rtype: string
        """
        ...
    
    @content.setter
    def content(self, value): # -> None:
        """The actual HTML content.

        :param value: The actual HTML content.
        :type value: string
        """
        ...
    
    def get(self): # -> dict[Any, Any]:
        """
        Get a JSON-ready representation of this HtmlContent.

        :returns: This HtmlContent, ready for use in a request body.
        :rtype: dict
        """
        ...
    


