"""
This type stub file was generated by pyright.
"""

class IpPoolName:
    """The IP Pool that you would like to send this email from."""
    def __init__(self, ip_pool_name=...) -> None:
        """Create a IpPoolName object

        :param ip_pool_name: The IP Pool that you would like to send this
                             email from.
        :type ip_pool_name: string, optional
        """
        ...
    
    @property
    def ip_pool_name(self): # -> None:
        """The IP Pool that you would like to send this email from.

        :rtype: string
        """
        ...
    
    @ip_pool_name.setter
    def ip_pool_name(self, value): # -> None:
        """The IP Pool that you would like to send this email from.

        :param value: The IP Pool that you would like to send this email from.
        :type value: string
        """
        ...
    
    def get(self): # -> None:
        """
        Get a JSON-ready representation of this IpPoolName.

        :returns: This IpPoolName, ready for use in a request body.
        :rtype: string
        """
        ...
    


