"""
This type stub file was generated by pyright.
"""

from .content import Content

class PlainTextContent(Content):
    """Plain text content to be included in your email.
    """
    def __init__(self, content) -> None:
        """Create a PlainTextContent with the specified MIME type and content.

        :param content: The actual text content.
        :type content: string
        """
        ...
    
    @property
    def mime_type(self): # -> Literal['text/plain']:
        """The MIME type.

        :rtype: string
        """
        ...
    
    @property
    def content(self): # -> None:
        """The actual text content.

        :rtype: string
        """
        ...
    
    @content.setter
    def content(self, value): # -> None:
        """The actual text content.

        :param value: The actual text content.
        :type value: string
        """
        ...
    
    def get(self): # -> dict[Any, Any]:
        """
        Get a JSON-ready representation of this PlainTextContent.

        :returns: This PlainTextContent, ready for use in a request body.
        :rtype: dict
        """
        ...
    


