"""
This type stub file was generated by pyright.
"""

class SandBoxMode:
    """Setting for sandbox mode.
    This allows you to send a test email to ensure that your request body is
    valid and formatted correctly.
    """
    def __init__(self, enable=...) -> None:
        """Create an enabled or disabled SandBoxMode.

        :param enable: Whether this is a test request.
        :type enable: boolean, optional
        """
        ...
    
    @property
    def enable(self): # -> None:
        """Indicates if this setting is enabled.

        :rtype: boolean
        """
        ...
    
    @enable.setter
    def enable(self, value): # -> None:
        """Indicates if this setting is enabled.

        :param value: Indicates if this setting is enabled.
        :type value: boolean
        """
        ...
    
    def get(self): # -> dict[Any, Any]:
        """
        Get a JSON-ready representation of this SandBoxMode.

        :returns: This SandBoxMode, ready for use in a request body.
        :rtype: dict
        """
        ...
    


