"""
This type stub file was generated by pyright.
"""

class Section:
    """A block section of code to be used as a substitution."""
    def __init__(self, key=..., value=...) -> None:
        """Create a section with the given key and value.

        :param key: section of code key
        :type key: string
        :param value: section of code value
        :type value: string
        """
        ...
    
    @property
    def key(self): # -> None:
        """A section of code's key.

        :rtype key: string
        """
        ...
    
    @key.setter
    def key(self, value): # -> None:
        """A section of code's key.

        :param key: section of code key
        :type key: string
        """
        ...
    
    @property
    def value(self): # -> None:
        """A section of code's value.

        :rtype: string
        """
        ...
    
    @value.setter
    def value(self, value): # -> None:
        """A section of code's value.

        :param value: A section of code's value.
        :type value: string
        """
        ...
    
    def get(self): # -> dict[Any, Any]:
        """
        Get a JSON-ready representation of this Section.

        :returns: This Section, ready for use in a request body.
        :rtype: dict
        """
        ...
    


