"""
This type stub file was generated by pyright.
"""

class SendAt:
    """A unix timestamp allowing you to specify when you want your
    email to be delivered. This may be overridden by the
    personalizations[x].send_at parameter. You can't schedule more
    than 72 hours in advance. If you have the flexibility, it's
    better to schedule mail for off-peak times. Most emails are
    scheduled and sent at the top of the hour or half hour.
    Scheduling email to avoid those times (for example, scheduling
    at 10:53) can result in lower deferral rates because it won't
    be going through our servers at the same times as everyone else's
    mail."""
    def __init__(self, send_at=..., p=...) -> None:
        """Create a unix timestamp specifying when your email should
        be delivered.

        :param send_at: Unix timestamp
        :type send_at: integer
        :param name: p is the Personalization object or Personalization object
                     index
        :type name: Personalization, integer, optional
        """
        ...
    
    @property
    def send_at(self): # -> None:
        """A unix timestamp.

        :rtype: integer
        """
        ...
    
    @send_at.setter
    def send_at(self, value): # -> None:
        """A unix timestamp.

        :param value: A unix timestamp.
        :type value: integer
        """
        ...
    
    @property
    def personalization(self): # -> None:
        """The Personalization object or Personalization object index

        :rtype: Personalization, integer
        """
        ...
    
    @personalization.setter
    def personalization(self, value): # -> None:
        """The Personalization object or Personalization object index

        :param value: The Personalization object or Personalization object
                      index
        :type value: Personalization, integer
        """
        ...
    
    def __str__(self) -> str:
        """Get a JSON representation of this object.

        :rtype: integer
        """
        ...
    
    def get(self): # -> None:
        """
        Get a JSON-ready representation of this SendAt object.

        :returns: The unix timestamp, ready for use in a request body.
        :rtype: integer
        """
        ...
    


