"""
This type stub file was generated by pyright.
"""

class SpamUrl:
    """An Inbound Parse URL that you would like a copy of your email
       along with the spam report to be sent to."""
    def __init__(self, spam_url=...) -> None:
        """Create a SpamUrl object

        :param spam_url: An Inbound Parse URL that you would like a copy of
                         your email along with the spam report to be sent to.
        :type spam_url: string, optional
        """
        ...
    
    @property
    def spam_url(self): # -> None:
        """An Inbound Parse URL that you would like a copy of your email
           along with the spam report to be sent to.

        :rtype: string
        """
        ...
    
    @spam_url.setter
    def spam_url(self, value): # -> None:
        """An Inbound Parse URL that you would like a copy of your email
           along with the spam report to be sent to.

        :param value: An Inbound Parse URL that you would like a copy of your
                      email along with the spam report to be sent to.
        :type value: string
        """
        ...
    
    def get(self): # -> None:
        """
        Get a JSON-ready representation of this SpamUrl.

        :returns: This SpamUrl, ready for use in a request body.
        :rtype: string
        """
        ...
    


