"""
This type stub file was generated by pyright.
"""

class SpamThreshold:
    """The threshold used to determine if your content qualifies as spam
       on a scale from 1 to 10, with 10 being most strict, or most likely
       to be considered as spam."""
    def __init__(self, spam_threshold=...) -> None:
        """Create a SpamThreshold object

        :param spam_threshold: The threshold used to determine if your content
                               qualifies as spam on a scale from 1 to 10, with
                               10 being most strict, or most likely to be
                               considered as spam.
        :type spam_threshold: integer, optional
        """
        ...
    
    @property
    def spam_threshold(self): # -> None:
        """The threshold used to determine if your content
           qualifies as spam on a scale from 1 to 10, with
           10 being most strict, or most likely to be
           considered as spam.

        :rtype: integer
        """
        ...
    
    @spam_threshold.setter
    def spam_threshold(self, value): # -> None:
        """The threshold used to determine if your content
           qualifies as spam on a scale from 1 to 10, with
           10 being most strict, or most likely to be
           considered as spam.

        :param value: The threshold used to determine if your content
        qualifies as spam on a scale from 1 to 10, with
        10 being most strict, or most likely to be
        considered as spam.
        :type value: integer
        """
        ...
    
    def get(self): # -> None:
        """
        Get a JSON-ready representation of this SpamThreshold.

        :returns: This SpamThreshold, ready for use in a request body.
        :rtype: integer
        """
        ...
    


