"""
This type stub file was generated by pyright.
"""

class Subject:
    """A subject for an email message."""
    def __init__(self, subject, p=...) -> None:
        """Create a Subject.

        :param subject: The subject for an email
        :type subject: string
        :param name: p is the Personalization object or Personalization object
                     index
        :type name: Personalization, integer, optional
        """
        ...
    
    @property
    def subject(self): # -> None:
        """The subject of an email.

        :rtype: string
        """
        ...
    
    @subject.setter
    def subject(self, value): # -> None:
        """The subject of an email.

        :param value: The subject of an email.
        :type value: string
        """
        ...
    
    @property
    def personalization(self): # -> None:
        """The Personalization object or Personalization object index

        :rtype: Personalization, integer
        """
        ...
    
    @personalization.setter
    def personalization(self, value): # -> None:
        """The Personalization object or Personalization object index

        :param value: The Personalization object or Personalization object
                      index
        :type value: Personalization, integer
        """
        ...
    
    def __str__(self) -> str:
        """Get a JSON representation of this Mail request.

        :rtype: string
        """
        ...
    
    def get(self): # -> None:
        """
        Get a JSON-ready representation of this Subject.

        :returns: This Subject, ready for use in a request body.
        :rtype: string
        """
        ...
    


