"""
This type stub file was generated by pyright.
"""

class SubscriptionText:
    """The text of an SubscriptionTracking."""
    def __init__(self, subscription_text=...) -> None:
        """Create a SubscriptionText object

        :param subscription_text: Text to be appended to the email, with the
                                  subscription tracking link. You may control
                                  where the link is by using the tag <% %>
        :type subscription_text: string, optional
        """
        ...
    
    @property
    def subscription_text(self): # -> None:
        """Text to be appended to the email, with the subscription tracking link.
           You may control where the link is by using the tag <% %>

        :rtype: string
        """
        ...
    
    @subscription_text.setter
    def subscription_text(self, value): # -> None:
        """Text to be appended to the email, with the subscription tracking link.
           You may control where the link is by using the tag <% %>

        :param value: Text to be appended to the email, with the subscription
                      tracking link. You may control where the link is by using
                      the tag <% %>
        :type value: string
        """
        ...
    
    def get(self): # -> None:
        """
        Get a JSON-ready representation of this SubscriptionText.

        :returns: This SubscriptionText, ready for use in a request body.
        :rtype: string
        """
        ...
    


