"""
This type stub file was generated by pyright.
"""

class SubscriptionSubstitutionTag:
    """The subscription substitution tag of an SubscriptionTracking."""
    def __init__(self, subscription_substitution_tag=...) -> None:
        """Create a SubscriptionSubstitutionTag object

        :param subscription_substitution_tag: A tag that will be replaced with
                                              the unsubscribe URL. for example:
                                              [unsubscribe_url]. If this
                                              parameter is used, it will
                                              override both the text and html
                                              parameters. The URL of the link
                                              will be placed at the
                                              substitution tag's location,
                                              with no additional formatting.
        :type subscription_substitution_tag: string, optional
        """
        ...
    
    @property
    def subscription_substitution_tag(self): # -> None:
        """A tag that will be replaced with the unsubscribe URL. for example:
           [unsubscribe_url]. If this parameter is used, it will override both
           the text and html parameters. The URL of the link will be placed at
           the substitution tag's location, with no additional formatting.

        :rtype: string
        """
        ...
    
    @subscription_substitution_tag.setter
    def subscription_substitution_tag(self, value): # -> None:
        """A tag that will be replaced with the unsubscribe URL. for example:
           [unsubscribe_url]. If this parameter is used, it will override both
           the text and html parameters. The URL of the link will be placed at
           the substitution tag's location, with no additional formatting.

        :param value: A tag that will be replaced with the unsubscribe URL.
                      for example: [unsubscribe_url]. If this parameter is
                      used, it will override both the text and html parameters.
                      The URL of the link will be placed at the substitution
                      tag's location, with no additional formatting.
        :type value: string
        """
        ...
    
    def get(self): # -> None:
        """
        Get a JSON-ready representation of this SubscriptionSubstitutionTag.

        :returns: This SubscriptionSubstitutionTag, ready for use in a request
                  body.
        :rtype: string
        """
        ...
    


