"""
This type stub file was generated by pyright.
"""

class SubscriptionHtml:
    """The HTML of an SubscriptionTracking."""
    def __init__(self, subscription_html=...) -> None:
        """Create a SubscriptionHtml object

        :param subscription_html: Html to be appended to the email, with the
                                  subscription tracking link. You may control
                                  where the link is by using the tag <% %>
        :type subscription_html: string, optional
        """
        ...
    
    @property
    def subscription_html(self): # -> None:
        """Html to be appended to the email, with the subscription tracking link.
           You may control where the link is by using the tag <% %>

        :rtype: string
        """
        ...
    
    @subscription_html.setter
    def subscription_html(self, value): # -> None:
        """Html to be appended to the email, with the subscription tracking link.
           You may control where the link is by using the tag <% %>

        :param value: Html to be appended to the email, with the subscription
                      tracking link. You may control where the link is by using
                      the tag <% %>
        :type value: string
        """
        ...
    
    def get(self): # -> None:
        """
        Get a JSON-ready representation of this SubscriptionHtml.

        :returns: This SubscriptionHtml, ready for use in a request body.
        :rtype: string
        """
        ...
    


