"""
This type stub file was generated by pyright.
"""

class Substitution:
    """A string substitution to be applied to the text and HTML contents of
    the body of your email, as well as in the Subject and Reply-To parameters.
    """
    def __init__(self, key=..., value=..., p=...) -> None:
        """Create a Substitution with the given key and value.

        :param key: Text to be replaced with "value" param
        :type key: string, optional
        :param value: Value to substitute into email
        :type value: string, optional
        :param name: p is the Personalization object or Personalization object
                     index
        :type name: Personalization, integer, optional
        """
        ...
    
    @property
    def key(self): # -> None:
        """The substitution key.

        :rtype key: string
        """
        ...
    
    @key.setter
    def key(self, value): # -> None:
        """The substitution key.

        :param key: The substitution key.
        :type key: string
        """
        ...
    
    @property
    def value(self): # -> str | None:
        """The substitution value.

        :rtype value: string
        """
        ...
    
    @value.setter
    def value(self, value): # -> None:
        """The substitution value.

        :param value: The substitution value.
        :type value: string
        """
        ...
    
    @property
    def personalization(self): # -> None:
        """The Personalization object or Personalization object index

        :rtype: Personalization, integer
        """
        ...
    
    @personalization.setter
    def personalization(self, value): # -> None:
        """The Personalization object or Personalization object index

        :param value: The Personalization object or Personalization object
                      index
        :type value: Personalization, integer
        """
        ...
    
    def get(self): # -> dict[Any, Any]:
        """
        Get a JSON-ready representation of this Substitution.

        :returns: This Substitution, ready for use in a request body.
        :rtype: dict
        """
        ...
    


