"""
This type stub file was generated by pyright.
"""

class SubscriptionTracking:
    """Allows you to insert a subscription management link at the bottom of the
    text and html bodies of your email. If you would like to specify the
    location of the link within your email, you may use the substitution_tag.
    """
    def __init__(self, enable=..., text=..., html=..., substitution_tag=...) -> None:
        """Create a SubscriptionTracking to customize subscription management.

        :param enable: Whether this setting is enabled.
        :type enable: boolean, optional
        :param text: Text to be appended to the email with the link as "<% %>".
        :type text: SubscriptionText, optional
        :param html: HTML to be appended to the email with the link as "<% %>".
        :type html: SubscriptionHtml, optional
        :param substitution_tag: Tag replaced with URL. Overrides text, html
                                 params.
        :type substitution_tag: SubscriptionSubstitutionTag, optional
        """
        ...
    
    @property
    def enable(self): # -> None:
        """Indicates if this setting is enabled.

        :rtype: boolean
        """
        ...
    
    @enable.setter
    def enable(self, value): # -> None:
        """Indicates if this setting is enabled.

        :param value: Indicates if this setting is enabled.
        :type value: boolean
        """
        ...
    
    @property
    def text(self): # -> None:
        """Text to be appended to the email, with the subscription tracking
        link. You may control where the link is by using the tag <% %>

        :rtype: string
        """
        ...
    
    @text.setter
    def text(self, value): # -> None:
        """Text to be appended to the email, with the subscription tracking
        link. You may control where the link is by using the tag <% %>

        :param value: Text to be appended to the email, with the subscription
                      tracking link. You may control where the link is by
                      using the tag <% %>
        :type value: string
        """
        ...
    
    @property
    def html(self): # -> None:
        """HTML to be appended to the email, with the subscription tracking
        link. You may control where the link is by using the tag <% %>

        :rtype: string
        """
        ...
    
    @html.setter
    def html(self, value): # -> None:
        """HTML to be appended to the email, with the subscription tracking
        link. You may control where the link is by using the tag <% %>

        :param value: HTML to be appended to the email, with the subscription
                      tracking link. You may control where the link is by
                      using the tag <% %>
        :type value: string
        """
        ...
    
    @property
    def substitution_tag(self): # -> None:
        """"A tag that will be replaced with the unsubscribe URL. for example:
        [unsubscribe_url]. If this parameter is used, it will override both the
        `text` and `html` parameters. The URL of the link will be placed at the
        substitution tag's location, with no additional formatting.

        :rtype: string
        """
        ...
    
    @substitution_tag.setter
    def substitution_tag(self, value): # -> None:
        """"A tag that will be replaced with the unsubscribe URL. for example:
        [unsubscribe_url]. If this parameter is used, it will override both the
        `text` and `html` parameters. The URL of the link will be placed at the
        substitution tag's location, with no additional formatting.

        :param value: A tag that will be replaced with the unsubscribe URL.
                      For example: [unsubscribe_url]. If this parameter is
                      used, it will override both the `text` and `html`
                      parameters. The URL of the link will be placed at the
                      substitution tag's location, with no additional
                      formatting.
        :type value: string
        """
        ...
    
    def get(self): # -> dict[Any, Any]:
        """
        Get a JSON-ready representation of this SubscriptionTracking.

        :returns: This SubscriptionTracking, ready for use in a request body.
        :rtype: dict
        """
        ...
    


