"""
This type stub file was generated by pyright.
"""

class TemplateId:
    """The template ID of an Attachment object."""
    def __init__(self, template_id=...) -> None:
        """Create a TemplateId object

        :param template_id: The template id for the message
        :type template_id: string, optional
        """
        ...
    
    @property
    def template_id(self): # -> None:
        """The template id for the message

        :rtype: string
        """
        ...
    
    @template_id.setter
    def template_id(self, value): # -> None:
        """The template id for the message

        :param value:  The template id for the message
        :type value: string
        """
        ...
    
    def get(self): # -> None:
        """
        Get a JSON-ready representation of this TemplateId.

        :returns: This TemplateId, ready for use in a request body.
        :rtype: string
        """
        ...
    


