"""
This type stub file was generated by pyright.
"""

class TrackingSettings:
    """Settings to track how recipients interact with your email."""
    def __init__(self, click_tracking=..., open_tracking=..., subscription_tracking=..., ganalytics=...) -> None:
        """Create a TrackingSettings object

        :param click_tracking: Allows you to track whether a recipient clicked
                               a link in your email.
        :type click_tracking: ClickTracking, optional
        :param open_tracking: Allows you to track whether the email was opened
                              or not, but including a single pixel image in
                              the body of the content. When the pixel is
                              loaded, we can log that the email was opened.
        :type open_tracking: OpenTracking, optional
        :param subscription_tracking: Allows you to insert a subscription
                                      management link at the bottom of the
                                      text and html bodies of your email. If
                                      you would like to specify the location
                                      of the link within your email, you may
                                      use the substitution_tag.
        :type subscription_tracking: SubscriptionTracking, optional
        :param ganalytics: Allows you to enable tracking provided by Google
                           Analytics.
        :type ganalytics: Ganalytics, optional
        """
        ...
    
    @property
    def click_tracking(self): # -> None:
        """Allows you to track whether a recipient clicked a link in your email.

        :rtype: ClickTracking
        """
        ...
    
    @click_tracking.setter
    def click_tracking(self, value): # -> None:
        """Allows you to track whether a recipient clicked a link in your email.

        :param value: Allows you to track whether a recipient clicked a link
                      in your email.
        :type value: ClickTracking
        """
        ...
    
    @property
    def open_tracking(self): # -> None:
        """Allows you to track whether a recipient opened your email.

        :rtype: OpenTracking
        """
        ...
    
    @open_tracking.setter
    def open_tracking(self, value): # -> None:
        """Allows you to track whether a recipient opened your email.

        :param value: Allows you to track whether a recipient opened your
                      email.
        :type value: OpenTracking
        """
        ...
    
    @property
    def subscription_tracking(self): # -> None:
        """Settings for the subscription management link.

        :rtype: SubscriptionTracking
        """
        ...
    
    @subscription_tracking.setter
    def subscription_tracking(self, value): # -> None:
        """Settings for the subscription management link.

        :param value: Settings for the subscription management link.
        :type value: SubscriptionTracking
        """
        ...
    
    @property
    def ganalytics(self): # -> None:
        """Settings for Google Analytics.

        :rtype: Ganalytics
        """
        ...
    
    @ganalytics.setter
    def ganalytics(self, value): # -> None:
        """Settings for Google Analytics.

        :param value: Settings for Google Analytics.
        :type value: Ganalytics
        """
        ...
    
    def get(self): # -> dict[Any, Any]:
        """
        Get a JSON-ready representation of this TrackingSettings.

        :returns: This TrackingSettings, ready for use in a request body.
        :rtype: dict
        """
        ...
    


