"""
This type stub file was generated by pyright.
"""

class UtmTerm:
    """The utm term of an Ganalytics object."""
    def __init__(self, utm_term=...) -> None:
        """Create a UtmTerm object

        :param utm_term: Used to identify any paid keywords.

        :type utm_term: string, optional
        """
        ...
    
    @property
    def utm_term(self): # -> None:
        """Used to identify any paid keywords.

        :rtype: string
        """
        ...
    
    @utm_term.setter
    def utm_term(self, value): # -> None:
        """Used to identify any paid keywords.

        :param value: Used to identify any paid keywords.
        :type value: string
        """
        ...
    
    def get(self): # -> None:
        """
        Get a JSON-ready representation of this UtmTerm.

        :returns: This UtmTerm, ready for use in a request body.
        :rtype: string
        """
        ...
    


