"""
This type stub file was generated by pyright.
"""

class UtmSource:
    """The utm source of an Ganalytics object."""
    def __init__(self, utm_source=...) -> None:
        """Create a UtmSource object

        :param utm_source: Name of the referrer source.
            (e.g. Google, SomeDomain.com, or Marketing Email)
        :type utm_source: string, optional
        """
        ...
    
    @property
    def utm_source(self): # -> None:
        """Name of the referrer source. (e.g. Google, SomeDomain.com, or
           Marketing Email)

        :rtype: string
        """
        ...
    
    @utm_source.setter
    def utm_source(self, value): # -> None:
        """Name of the referrer source. (e.g. Google, SomeDomain.com, or
           Marketing Email)

        :param value: Name of the referrer source.
        (e.g. Google, SomeDomain.com, or Marketing Email)
        :type value: string
        """
        ...
    
    def get(self): # -> None:
        """
        Get a JSON-ready representation of this UtmSource.

        :returns: This UtmSource, ready for use in a request body.
        :rtype: string
        """
        ...
    


