"""
This type stub file was generated by pyright.
"""

class UtmCampaign:
    """The utm campaign of an Ganalytics object."""
    def __init__(self, utm_campaign=...) -> None:
        """Create a UtmCampaign object

        :param utm_campaign: The name of the campaign

        :type utm_campaign: string, optional
        """
        ...
    
    @property
    def utm_campaign(self): # -> None:
        """The name of the campaign

        :rtype: string
        """
        ...
    
    @utm_campaign.setter
    def utm_campaign(self, value): # -> None:
        """The name of the campaign

        :param value: The name of the campaign
        :type value: string
        """
        ...
    
    def get(self): # -> None:
        """
        Get a JSON-ready representation of this UtmCampaign.

        :returns: This UtmCampaign, ready for use in a request body.
        :rtype: string
        """
        ...
    


