"""
This type stub file was generated by pyright.
"""

class UtmMedium:
    """The utm medium of an Ganalytics object."""
    def __init__(self, utm_medium=...) -> None:
        """Create a UtmMedium object

        :param utm_medium: Name of the marketing medium. (e.g. Email)

        :type utm_medium: string, optional
        """
        ...
    
    @property
    def utm_medium(self): # -> None:
        """Name of the marketing medium. (e.g. Email)

        :rtype: string
        """
        ...
    
    @utm_medium.setter
    def utm_medium(self, value): # -> None:
        """Name of the marketing medium. (e.g. Email)

        :param value: Name of the marketing medium. (e.g. Email)
        :type value: string
        """
        ...
    
    def get(self): # -> None:
        """
        Get a JSON-ready representation of this UtmMedium.

        :returns: This UtmMedium, ready for use in a request body.
        :rtype: string
        """
        ...
    


