"""
This type stub file was generated by pyright.
"""

class UtmContent:
    """The utm content of an Ganalytics object."""
    def __init__(self, utm_content=...) -> None:
        """Create a UtmContent object

        :param utm_content: Used to differentiate your campaign from advertisements.

        :type utm_content: string, optional
        """
        ...
    
    @property
    def utm_content(self): # -> None:
        """Used to differentiate your campaign from advertisements.

        :rtype: string
        """
        ...
    
    @utm_content.setter
    def utm_content(self, value): # -> None:
        """Used to differentiate your campaign from advertisements.

        :param value: Used to differentiate your campaign from advertisements.
        :type value: string
        """
        ...
    
    def get(self): # -> None:
        """
        Get a JSON-ready representation of this UtmContent.

        :returns: This UtmContent, ready for use in a request body.
        :rtype: string
        """
        ...
    


