"""
This type stub file was generated by pyright.
"""

class ValidateApiKey:
    """Validates content to ensure SendGrid API key is not present"""
    regexes = ...
    def __init__(self, regex_strings=..., use_default=...) -> None:
        """Create an API key validator

            :param regex_strings: list of regex strings
            :type regex_strings: list(str)
            :param use_default: Whether or not to include default regex
            :type use_default: bool
        """
        ...
    
    def validate_message_dict(self, request_body): # -> None:
        """With the JSON dict that will be sent to SendGrid's API,
            check the content for SendGrid API keys - throw exception if found.

           :param request_body: The JSON dict that will be sent to SendGrid's
                                API.
           :type request_body: JSON serializable structure
           :raise ApiKeyIncludedException: If any content in request_body
                                           matches regex
        """
        ...
    
    def validate_message_text(self, message_string): # -> None:
        """With a message string, check to see if it contains a SendGrid API Key
            If a key is found, throw an exception

           :param message_string: message that will be sent
           :type message_string: string
           :raises ApiKeyIncludedException: If message_string matches a regex
                                            string
        """
        ...
    


