"""
This type stub file was generated by pyright.
"""

class EventWebhookHeader:
    """
    This class lists headers that get posted to the webhook. Read the docs for
    more details: https://sendgrid.com/docs/for-developers/tracking-events/event
    """
    SIGNATURE = ...
    TIMESTAMP = ...
    def __init__(self) -> None:
        ...
    


